### ISSUE TITLE
Time 260

### ISSUE THREAD

**Issue by joel-holanda** [deco-sites/fashion#316]
Qual a section que voce esta fazendo?
Section CookieConsent (Cookie Consent) | HACKATHON https://github.com/deco-sites/fashion/issues/2155
Categoria 3 - CookieConsent
@joel-holanda 
@Kayquedias

- [ X] Estou usando tokens do DaisyUI e Tailwind CSS
- [ X] Fiz alterações **somente** no arquivo destinado a section do meu grupo
- [ X] O componente esta editável no admin da Deco
- [ X] Adicionei link de preview da section do admin da deco no PR
- [ X] Minha section funciona com propriedades padrão
- [ ] Adicionei links das variacoes do figma que fiz no PR

Link do Preview:
https://deco.cx/admin/sites/fashion/blocks/previews?ref=%23%2Fdefinitions%2FZGVjby1zaXRlcy9mYXNoaW9uL3NlY3Rpb25zL0Nvb2tpZUNvbnNlbnQvQ29va2llQ29uc2VudC5yb2NrZXRzcGFjZS50c3g%3D&type=CookieConsent

**Comment by guifromrio** [comment]
Oi @joel-holanda ! Obrigado por participar! O jeito de contribuir é criando um *pull request* do seu fork pra cá. Mas eu consegui clonar seu repo e revisar. Notei que as props não foram todas mapeadas pros textos. Mas ficou super legal pra um primeiro componente, parabens!
